version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  nestjs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      JWT_SECRET: ${JWT_SECRET}
      HASH_ROUNDS: ${HASH_ROUNDS}
      PROTOCOL: ${PROTOCOL}
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
